server:
  port: 8081
spring:
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: atum-service
          service-host-type: ip
        url: http://localhost:8085
  application:
    name: atum-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/atum
  datasource:
    url: jdbc:postgresql://localhost:5432/clothing_store_catalogue_db
    username: postgres
    password: glhf5561783742
  flyway:
    baseline-on-migrate: true
    schemas:
      - catalogue
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    sql: info