server:
  port: 8084
spring:
  boot:
    admin:
      client:
        url: http://localhost:8085
        instance:
          name: feedback-service
          service-host-type: ip
        enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/feedback-service-database
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/atum
      client:
        registration:
          keycloak:
            client-id: feedback-service-metrics-client
            client-secret: iveHdNE44BvDyLr5GylG8taTrFb49wwr
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/atum
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'