spring:
  boot:
    admin:
      client:
        url: http://localhost:8085
        instance:
          name: atum-service
          service-host-type: ip
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/atum
      client:
        registration:
          keycloak:
            client-id: atum-service-metrics-client
            client-secret: y7zGR9spcxlBA6cBRBcoQ4lEzzJhfNAF
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/atum
  datasource:
    url: jdbc:postgresql://localhost:5432/clothing_store_catalogue_db
    username: postgres
    password: glhf5561783742
  flyway:
    baseline-on-migrate: true
    schemas:
      - catalogue
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    sql: info
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'